RAVKAV_ISSUERS = {
    [0] = "undefined",
    [1] = "Service Center (Postal Bank)",
    [2] = "Israel Railways",
    [3] = "Egged",
    [4] = "Egged Transport",
    [5] = "Dan",
    [6] = "NTT (United Bus Services Nazareth)",
    [7] = "NTT (Nazareth Travel & Tourism)",
    [8] = "GB Tours",
    [9] = "Omni Nazrin Express (transferred to Nativ Express)",
    [10] = "Eilot Regional Council",
    [11] = "Illit (merged with Kavim)",
    [12] = "undefined 12",
    [13] = "undefined 13",
    [14] = "Nativ Express",
    [15] = "Metropoline",
    [16] = "Superbus",
    [17] = "Connex Veolia (transferred to Afikim)",
    [18] = "Kavim",
    [19] = "Metrodan (defunct, transferred to Dan Be'er Sheva)",
    [20] = "Carmelit",
    [21] = "CityPass",
    [22] = "Tel Aviv Light Rail operator",     --name undecided yet but id is set
    [23] = "Galim (Narkis Gal)",
    [24] = "Golan Regional Council",
    [25] = "Afikim",
    [26] = "undefined 26",
    [27] = "undefined 27",
    [28] = "undefined 28",
    [29] = "undefined 29",
    [30] = "Dan North",
    [31] = "Dan South",
    [32] = "Dan Be'er Sheva",
    [33] = "undefined 33",
    [34] = "undefined 34",
    [35] = "undefined 35",
    [36] = "undefined 36",
    [37] = "undefined 37",
    [38] = "undefined 38",
    [39] = "undefined 39",
    [40] = "undefined 40",
    [41] = "East Jerusalem operators",
    [42] = "Jerusalem - Ramallah united",
    [43] = "Jerusalem - Mahane Shuafat",
    [44] = "Jerusalem - Abu-Tor - Anata united",
    [45] = "Jerusalem - Alwest united",
    [46] = "reserved 46",
    [47] = "Jerusalem - Mount of Olives",
    [48] = "reserved 48",
    [49] = "reserved 49",
    [50] = "South Jerusalem united",
    [51] = "Jerusalem - Sur Baher united",
    [52] = "reserved 52",
    [53] = "Jerusalem - Isawiya",
--  101-157 reserved
    [250] = "Israel Defence Forces"
}

RAVKAV_COMPANIES = {
    [0] = "None",
    [256] = "[256] - Israel Police",
    [257] = "[257] - Prison Services",
    [258] = "[258] - Israel Defence Forces",
    [260] = "[260] - Extended student citizens of Eilat and Arava",
    [261] = "[261] - Standard student citizens of Eilat and Arava",
    [269] = "[269] - Parliament Guard",
    [270] = "[270] - Identification by means of foreign passport",
    [275] = "[275] - School for Special Education: Magen HaLev Ashdod",
    [280] = "[280] - Companies partnered with Israel Railways",
    [281] = "[281] - Companies partnered with Israel Railways",
    [282] = "[282] - Companies partnered with Israel Railways",
    [283] = "[283] - Companies partnered with Israel Railways",
    [284] = "[284] - Companies partnered with Israel Railways",
    [285] = "[285] - Companies partnered with Israel Railways",
    [286] = "[286] - Companies partnered with Israel Railways",
    [287] = "[287] - Companies partnered with Israel Railways",
    [288] = "[288] - Companies partnered with Israel Railways",
    [289] = "[289] - Companies partnered with Israel Railways",
    [290] = "[290] - Companies partnered with Israel Railways",
    [291] = "[291] - Companies partnered with Israel Railways",
    [292] = "[292] - Companies partnered with Israel Railways",
    [293] = "[293] - Companies partnered with Israel Railways",
    [294] = "[294] - Companies partnered with Israel Railways",
    [295] = "[295] - Companies partnered with Israel Railways",
    [296] = "[296] - Companies partnered with Israel Railways",
    [297] = "[297] - Companies partnered with Israel Railways",
    [298] = "[298] - Companies partnered with Israel Railways",
    [299] = "[299] - Companies partnered with Israel Railways"
}

RAVKAV_PROFILES = {
    [0] = "Standard",
    [1] = "Adult",
    [2] = "Child",
    [3] = "Extended Student",
    [4] = "Senior Citizen",
    [5] = "Handicapped",
    [6] = "Poor vision / Blind",
    [7] = "Deaf / Dumb",
    [8] = "Unemployed",
    [9] = "Personal",
    [10] = "Israel Defence Forces / Ministry of Defence / Security personnel",
    [11] = "Resident",
    [12] = "Transport",
    [13] = "Public Transport Employee",
    [14] = "Long-term transport",
    [15] = "Local transport",
    [16] = "Commuter",
    [17] = "Animal",
    [18] = "Object",
    [19] = "Standard Student",
    [20] = "20",
    [21] = "21",
    [22] = "22",
    [23] = "23",
    [24] = "24",
    [25] = "25",
    [26] = "26",
    [27] = "27",
    [28] = "28",
    [29] = "29",
    [30] = "30",
    [31] = "31",
    [32] = "Child aged 5-10",
    [33] = "Youth aged 5-18",
    [34] = "National Service",
    [35] = "Service without pay (SHALAT) / Pre-Army Course (KADATS)",
    [36] = "Israel Police",
    [37] = "Prison Services",
    [38] = "Member of Parliament",
    [39] = "Parliament Guard",
    [40] = "Eligible for Social Security",
    [41] = "Victim of Hostilities",
    [42] = "New Immigrant in Rural Settlement",
    [43] = "Person Accompanying Poor vision / Blind",
    [44] = "44",
    [45] = "45",
    [46] = "46",
    [47] = "47",
    [48] = "48",
    [49] = "49",
    [50] = "50",
    [51] = "51",
    [52] = "52",
    [53] = "Residents of the South [Israel Railways]",
    [54] = "Residents of the Valley [Israel Railways]",
    [55] = "Child aged 0-4",
    [56] = "56",
    [57] = "57",
    [58] = "58",
    [59] = "Youth Student on Intercity Ride"
}

--Cluster codes
--issuerId:
--[code] = description --issuerId
RAVKAV_ROUTES = {
    --18:
    [1] = "Ha'Emek",
    --5:
    [11] = "Dan Region - Tel-Aviv",                        -- from July 1, 2012
    [12] = "Dan Region - Ever Ha'Yarkon",                  -- from July 1, 2012
    [13] = "Dan Region East - Bnei Brak",                  -- from July 1, 2012
    [14] = "Dan Region East - Ramat Gan",                  -- from July 1, 2012
    [15] = "Dan Region South - Bat Yam",                   -- from July 1, 2012
    [16] = "Dan Region South - Rishon Le'Tziyon / Holon",  -- from July 1, 2012
    [17] = "Petah-Tikva - Tel-Aviv",                       -- from July 1, 2012
    [18] = "Youth students",                               -- from July 1, 2012
    [19] = "Bat Yam - Ramat Gan",                          -- from July 1, 2012
    [40] = "reserved",
    --2:
    [50] = "Israel Railways - Primary",
    [51] = "Israel Railways - Northern",
    [52] = "Israel Railways - Central",
    [53] = "Israel Railways - Southern",
    [54] = "Israel Railways - Palestine",
    [55] = "reserved",
    --3:
    [71] = "Holon urban + metropolis + competition",
    [72] = "Rishon Le'Tziyon suburban",
    [73] = "Rishon Le'Tziyon urban",
    [74] = "Rehovot urban",
    [75] = "Rehovot suburban",
    [76] = "Tel-Aviv - Ashkelon",
    [77] = "Tel-Aviv - Galilee - Amekim",
    [79] = "Ashdod youth students",
    [81] = "Haifa urban",
    [83] = "Haifa suburban",
    [84] = "Kiryat Shmona - Haifa",
    [85] = "From CBS Krayot",
    [86] = "Hadera suburban",
    [87] = "Kiryat Shmona urban",
    [89] = "Carmiel urban, Carmiel - Haifa, Haifa - Tiberias",
    [91] = "Jerusalem urban",
    [93] = "Jerusalem - Beit Shemesh",
    [94] = "Jerusalem - Tel-Aviv",
    [95] = "Jerusalem - Bnei Brak (402)",
    [96] = "Jerusalem - Ha'Shfela",
    [97] = "Jerusalem North - east axis",
    [98] = "Ashdod - Ashkelon - Jerusalem",
    [101] = "Eilat urban and intercity",
    [102] = "Southern cluster",
    [103] = "Haifa - Ha'Sharon - Jerusalem",
    [104] = "Jerusalem - Be'er Sheva",
    [105] = "Jerusalem - Bnei Brak (400)",
    [106] = "Ashdod - Tel-Aviv (competition)",
    [107] = "Nahariya - Haifa (competition)",
    [108] = "Shfar'am Villages (competition)",
    [109] = "Safed (competition)",
    [110] = "Tel-Aviv - Ha'Sharon - Haifa",
    [111] = "Tel-Aviv - Hadera",
    [112] = "Haredi lines (competition)",
    [113] = "Jerusalem suburban",
    [114] = "Jerusalem protected",
    [115] = "Jerusalem - Haredi lines",             --4
    [116] = "Netanya - Hadera (competition)",
    [117] = "500 lines (competition)",
    [118] = "Haifa - Jerusalem - Eilat",

    [120] = "HaAmakim",                             --16
    [121] = "Nazareth lines - GB Tours",            --8
    [122] = "Nazareth lines - NTT (Travel and Tourism)",--7
    [123] = "Nazareth lines - NTT (United Bus Services Nazareth)",--6
    [124] = "Nahariya - Safed",                     --14
    [125] = "Nazareth-Haifa shared",                --7
    [126] = "Nazareth-Haifa shared",                --8
    [127] = "Yokneam - Tiv'on",                     --9, 14 (merge of Omni with Nativ Express)
    [128] = "Galilee",                              --14
    [130] = "Golan Heights",                        --24
    [132] = "Nazareth area - GB Tours",             --8
    [140] = "Southern cluster - Negev",             --15
    [141] = "Ha'Negev North",                       --31
    [142] = "Eilot",                                --10
    [143] = "Rahat",                                --23
    [150] = "Hashmonaim",                           --18
    [151] = "Elad",                                 --4
    [152] = "Beitar Illit",                         --11, 18 (since July 1, 2012, merge of Illit with Kavim)
    [153] = "Beitar Illit",                         --11, 18 (since July 1, 2012, merge of Illit with Kavim)
    [154] = "Modi'in",                              --17
    [155] = "Hadera - Netanya",                     --18
    [156] = "Hadera - Netanya (future)",            --18
    [157] = "Modi'in Illit",                        --16
    [158] = "Yavne - Ashdod - Tel-Aviv",            --17
    [160] = "Netanya - Tel-Aviv",                   --14
    [169] = "Lod - Tel-Aviv",                       --17
    [170] = "Peruzdor Jerusalem",                   --16
    [171] = "Hwy 4 - Jerusalem - Bnei Brak",        --17
    [176] = "Jerusalem perimeter",                  --4
    [180] = "East Jerusalem",                       --41
    [190] = "Samaria",                              --25
    [195] = "Ha'Sharon",                            --15
    [200] = "Dan Region",                           --5
    [201] = "Be'er Sheva urban",                    --32
    [202] = "Tiberias regional",                    --17
    [203] = "Ramla - Lod",                          --16
    [204] = "Ashdod urban",                         --25
    [205] = "Netanya urban",                        --4
    [206] = "Fast Lane Shuttle",                    --5
    [207] = "Petah-Tikva - Rosh Ha'Ayin",           --25
    [208] = "Ono - Petah-Tikva",                    --18
    [209] = "Ono - Elad",                           --18
    [210] = "Jerusalem Light Rail",                 --21
    [214] = "Carmelit",                             --20
    [215] = "Metronit Haifa",                       --30
    [218] = "Fast line Tel-Aviv (BRT)",             --5
    [220] = "Tel-Aviv Light Rail",                  --?
    [221] = "Direct Be'er Sheva - Tel-Aviv",        --4 (until October 2013)
    [222] = "Be'er Sheva - Tel-Aviv - Negev (including Arad, Yeruham, Mitzpe Ramon and Nitzana)", --15

--Sherut Taxis
    [249] = "Sherut Taxis"
}

-- These are the station names from the Israel Rail website.
-- However the IDs on the website do NOT match those used by RavKav and are incorrect,
-- except for the 63 that have been updated below (with original ID added as comment)
RAVKAV_RAIL_LOCATIONS = {
-- 2: Israel Railways:
    [1]  =     "[Ticketing Machine] Tel Aviv Center - Savidor",      --3700
    [2]  =     "[Ticketing Machine] Herzliya",                       --3500
    [3]  =     "[Ticketing Machine] Beit Yehoshua",                  --3400
    [4]  =     "[Ticketing Machine] Netanya",                        --3300
    [5]  =     "[Ticketing Machine] Hadera West",                    --3100
    [6]  =     "[Ticketing Machine] Binyamina",                      --2800
    [7]  =     "[Ticketing Machine] Ceasarea - Pardes Hana",         --2820
    [8]  =     "[Ticketing Machine] Atlit",                          --2500
    [9]  =     "[Ticketing Machine] Haifa Bat Galim",                --2200
    [10] =     "[Ticketing Machine] Haifa - Hutsot HaMifrats",       --1300
    [11] =     "[Ticketing Machine] Kiryat Hayim",                   --700
    [12] =     "[Ticketing Machine] Kiryat Motzkin",                 --800
    [13] =     "[Ticketing Machine] Akko",                           --1500
    [14] =     "[Ticketing Machine] Haifa Hof HaKarmel (Razi'el)",   --2300
    [15] =     "[Ticketing Machine] Kfar Saba - Nordau (A. Kostyuk)",--8700
    [16] =     "[Ticketing Machine] Nahariya",                       --1600
    [17] =     "[Ticketing Machine] Jerusalem Biblical Zoo",         --6500
    [18] =     "[Ticketing Machine] Beit Shemesh",                   --6300
    [19] =     "[Ticketing Machine] Kiryat Gat",                     --7000
    [20] =     "[Ticketing Machine] Lod",                            --5000
    [21] =     "[Ticketing Machine] Be'er Sheva North / University", --7300
    [22] =     "[Ticketing Machine] Kfar Habbad",                    --4800
    [23] =     "[Ticketing Machine] Tel Aviv HaShalom",              --4600
    [24] =     "[Ticketing Machine] Haifa East",                     --
    [25] =     "[Ticketing Machine] Haifa Center HaShmona",          --2100
    [26] =     "[Ticketing Machine] Ramla",                          --5010
    [27] =     "[Ticketing Machine] Rosh Ha'Ayin North",             --8800
    [28] =     "[Ticketing Machine] Be'er Ya'akov",                  --5300
    [29] =     "[Ticketing Machine] Rehovot E. Hadar",               --5200
    [30] =     "[Ticketing Machine] Yavne East",                     --5410
    [31] =     "[Ticketing Machine] Rishon Le'Tziyon - HaRishonim",  --9100
    [32] =     "[Ticketing Machine] Ashdod Ad Halom (M. Bar Kochva)",--5800
    [33] =     "[Ticketing Machine] Rosh Ha'Ayin South",             --
    [34] =     "[Ticketing Machine] Petah-Tikva - Sgula",            --4250
    [35] =     "[Ticketing Machine] Bnei Brak",                      --4100
    [36] =     "[Ticketing Machine] Tel Aviv - University",          --3600
    [37] =     "[Ticketing Machine] Be'er Sheva Center",             --7320
    [38] =     "[Ticketing Machine] Haifa - Lev HaMifrats",          --1220
    [39] =     "[Ticketing Machine] Tel Aviv HaHagana",              --4900
    [40] =     "[Ticketing Machine] Ben Gurion Airport",             --8600
    [41] =     "[Ticketing Machine] Jerusalem Malha",                --6700
    [42] =     "[Ticketing Machine] Ashkelon",                       --5900
    [43] =     "[Ticketing Machine] Dimona",                         --7500
    [44] =     "[Ticketing Machine] Hod HaSharon - Sokolov",         --9200
    [45] =     "[Ticketing Machine] Petah-Tikva - Kiryat Arye",      --4170
    [46] =     "[Ticketing Machine] Lod Ganey Aviv",                 --5150
    [47] =     "[Ticketing Machine] Lehavim - Rahat",                --8550
    [48] =     "[Ticketing Machine] Modi'in - Pa'atei Modi'in",      --300
    [49] =     "[Ticketing Machine] Modi'in Center",                 --400
    [50] =     "[Ticketing Machine] Holon Junction",                 --4640
    [51] =     "[Ticketing Machine] Holon - Wolfson",                --4660
    [52] =     "[Ticketing Machine] Bat Yam - Yoseftal",             --4680
    [53] =     "[Ticketing Machine] Bat Yam - Komemiyyut",           --4690
    [54] =     "[Ticketing Machine] Rishon Le'Tziyon - Moshe Dayan", --9800
    [55] =     "[Ticketing Machine] Yavne West",                     --9000
    [56] =     "[Ticketing Machine] Sderot",                         --9600
    [57] =     "[Ticketing Machine] Netivot",                        --9650
    --check
    [58] =     "[Ticketing Machine] Ofakim",                         --9700
    [59] =     "[Ticketing Machine] ",                               --
    [60] =     "[Ticketing Machine] Yokneam - Kfar Yehoshua",        --1240
    [61] =     "[Ticketing Machine] ",                               --
    [62] =     "[Ticketing Machine] ",                               --
    [63] =     "[Ticketing Machine] ",                               --

    [7001] =   "Tel Aviv Center - Savidor",                          --3700
    [7002] =   "Herzliya",                                           --3500
    [7003] =   "Beit Yehoshua",                                      --3400
    [7004] =   "Netanya",                                            --3300
    [7005] =   "Hadera West",                                        --3100
    [7006] =   "Binyamina",                                          --2800
    [7007] =   "Ceasarea - Pardes Hana",                             --2820
    [7008] =   "Atlit",                                              --2500
    [7009] =   "Haifa Bat Galim",                                    --2200
    [7010] =   "Haifa - Hutsot HaMifrats",                           --1300
    [7011] =   "Kiryat Hayim",                                       --700
    [7012] =   "Kiryat Motzkin",                                     --800
    [7013] =   "Akko",                                               --1500
    [7014] =   "Haifa Hof HaKarmel (Razi'el)",                       --2300
    [7015] =   "Kfar Saba - Nordau (A. Kostyuk)",                    --8700
    [7016] =   "Nahariya",                                           --1600
    [7017] =   "Jerusalem Biblical Zoo",                             --6500
    [7018] =   "Beit Shemesh",                                       --6300
    [7019] =   "Kiryat Gat",                                         --7000
    [7020] =   "Lod",                                                --5000
    [7021] =   "Be'er Sheva North / University",                     --7300
    [7022] =   "Kfar Habbad",                                        --4800
    [7023] =   "Tel Aviv HaShalom",                                  --4600
    [7024] =   "Haifa East",                                         --
    [7025] =   "Haifa Center HaShmona",                              --2100
    [7026] =   "Ramla",                                              --5010
    [7027] =   "Rosh Ha'Ayin North",                                 --8800
    [7028] =   "Be'er Ya'akov",                                      --5300
    [7029] =   "Rehovot E. Hadar",                                   --5200
    [7030] =   "Yavne East",                                         --5410
    [7031] =   "Rishon Le'Tziyon - HaRishonim",                      --9100
    [7032] =   "Ashdod Ad Halom (M. Bar Kochva)",                    --5800
    [7033] =   "Rosh Ha'Ayin South",                                 --
    [7034] =   "Petah-Tikva - Sgula",                                --4250
    [7035] =   "Bnei Brak",                                          --4100
    [7036] =   "Tel Aviv - University",                              --3600
    [7037] =   "Be'er Sheva Center",                                 --7320
    [7038] =   "Haifa - Lev HaMifrats",                              --1220
    [7039] =   "Tel Aviv HaHagana",                                  --4900
    [7040] =   "Ben Gurion Airport",                                 --8600
    [7041] =   "Jerusalem Malha",                                    --6700
    [7042] =   "Ashkelon",                                           --5900
    [7043] =   "Dimona",                                             --7500
    [7044] =   "Hod HaSharon - Sokolov",                             --9200
    [7045] =   "Petah-Tikva - Kiryat Arye",                          --4170
    [7046] =   "Lod Ganey Aviv",                                     --5150
    [7047] =   "Lehavim - Rahat",                                    --8550
    [7048] =   "Modi'in - Pa'atei Modi'in",                          --300
    [7049] =   "Modi'in Center",                                     --400
    [7050] =   "Holon Junction",                                     --4640
    [7051] =   "Holon - Wolfson",                                    --4660
    [7052] =   "Bat Yam - Yoseftal",                                 --4680
    [7053] =   "Bat Yam - Komemiyyut",                               --4690
    [7054] =   "Rishon Le'Tziyon - Moshe Dayan",                     --9800
    [7055] =   "Yavne West",                                         --9000
    [7056] =   "Sderot",                                             --9600
    [7057] =   "Netivot",                                            --9650
    --check
    [7058] =   "Ofakim",                                             --9700
    [7059] =   "7059",                                                   --
    [7060] =   "Yokneam - Kfar Yehoshua",                            --1240
    [7061] =   "7061",                                                   --
    [7062] =   "7062",                                                   --
    [7063] =   "7063",                                                   --

    [1250] =   "Migdal HaEmek - Kfar Barukh",
    [1260] =   "Afula",
    [1280] =   "Beit She'an",
    [3310] =   "Netanya Sapir"
}

RAVKAV_RAIL_LOCATIONS2 = {
-- 2: Israel Railways:
    [1]  =     "Tel Aviv Center - Savidor",      --3700
    [2]  =     "Herzliya",                       --3500
    [3]  =     "Beit Yehoshua",                  --3400
    [4]  =     "Netanya",                        --3300
    [5]  =     "Hadera West",                    --3100
    [6]  =     "Binyamina",                      --2800
    [7]  =     "Ceasarea - Pardes Hana",         --2820
    [8]  =     "Atlit",                          --2500
    [9]  =     "Haifa Bat Galim",                --2200
    [10] =     "Haifa - Hutsot HaMifrats",       --1300
    [11] =     "Kiryat Hayim",                   --700
    [12] =     "Kiryat Motzkin",                 --800
    [13] =     "Akko",                           --1500
    [14] =     "Haifa Hof HaKarmel (Razi'el)",   --2300
    [15] =     "Kfar Saba - Nordau (A. Kostyuk)",--8700
    [16] =     "Nahariya",                       --1600
    [17] =     "Jerusalem Biblical Zoo",         --6500
    [18] =     "Beit Shemesh",                   --6300
    [19] =     "Kiryat Gat",                     --7000
    [20] =     "Lod",                            --5000
    [21] =     "Be'er Sheva North / University", --7300
    [22] =     "Kfar Habbad",                    --4800
    [23] =     "Tel Aviv HaShalom",              --4600
    [24] =     "Haifa East",                     --
    [25] =     "Haifa Center HaShmona",          --2100
    [26] =     "Ramla",                          --5010
    [27] =     "Rosh Ha'Ayin North",             --8800
    [28] =     "Be'er Ya'akov",                  --5300
    [29] =     "Rehovot E. Hadar",               --5200
    [30] =     "Yavne East",                     --5410
    [31] =     "Rishon Le'Tziyon - HaRishonim",  --9100
    [32] =     "Ashdod Ad Halom (M. Bar Kochva)",--5800
    [33] =     "Rosh Ha'Ayin South",             --
    [34] =     "Petah-Tikva - Sgula",            --4250
    [35] =     "Bnei Brak",                      --4100
    [36] =     "Tel Aviv - University",          --3600
    [37] =     "Be'er Sheva Center",             --7320
    [38] =     "Haifa - Lev HaMifrats",          --1220
    [39] =     "Tel Aviv HaHagana",              --4900
    [40] =     "Ben Gurion Airport",             --8600
    [41] =     "Jerusalem Malha",                --6700
    [42] =     "Ashkelon",                       --5900
    [43] =     "Dimona",                         --7500
    [44] =     "Hod HaSharon - Sokolov",         --9200
    [45] =     "Petah-Tikva - Kiryat Arye",      --4170
    [46] =     "Lod Ganey Aviv",                 --5150
    [47] =     "Lehavim - Rahat",                --8550
    [48] =     "Modi'in - Pa'atei Modi'in",      --300
    [49] =     "Modi'in Center",                 --400
    [50] =     "Holon Junction",                 --4640
    [51] =     "Holon - Wolfson",                --4660
    [52] =     "Bat Yam - Yoseftal",             --4680
    [53] =     "Bat Yam - Komemiyyut",           --4690
    [54] =     "Rishon Le'Tziyon - Moshe Dayan", --9800
    [55] =     "Yavne West",                     --9000
    [56] =     "Sderot",                         --9600
    [57] =     "Netivot",                        --9650
    --check
    [58] =     "Ofakim",                         --9700
    [59] =     "59",                               --
    [60] =     "Yokneam - Kfar Yehoshua",        --1240
    [61] =     "61",                               --
    [62] =     "62",                               --
    [63] =     "63"                                --
}

--Bus stops
RAVKAV_BUS_LOCATIONS = {
     --adding full stop list here statically, causes
     --ERROR   backtrace: called at [C]
     --ERROR   backtrace: called from require()
     --ERROR   backtrace: called at calypso/c376.lua
     --ERROR   backtrace: called from dofile()
     --ERROR   backtrace: called from calypso_process() in [string "calypso.lua"][255]
     --ERROR   backtrace: called at [string "calypso.lua"]

     --require('etc.ravkav-strings') halts when the file is too big (3.5 MB)

     --for now use GTFS stops.txt

     --[stop_code] = "[stop_code] stop_name / stop_desc"
}

RAVKAV_LINE_TYPES = {
     [0] = "Not set or generic public transport",
     [1] = "Urban",
     [2] = "Regional",
     [3] = "Intercity",
     [4] = "Light Rail",
     [5] = "Intercity Rail",
     [15] = "Transport method"
}

RAVKAV_EVENT_TYPES = {
    [0]   = "Action -",
    [1]   = "Entry -",  --Used for
    [2]   = "Exit -",
    [3]   = "Transit -",
    [4]   = "Prevalidate -",
    [5]   = "Inspection -",
    [6]   = "Transit trip",
    [7]   = "Exit from station -",
    [8]   = "Other usage -",
    [9]   = "Contract cancel -",
    [12]  = "Contract load and used immediately for -",
    [13]  = "Contract load -",
    [14]  = "Personalization / Card issuance",
    [15]  = "Card invalidation"
}

RAVKAV_LOAD_EVENTS = {
    [0]    = "Contract load failure",
    [10]   = "Card is full",
    [11]   = "Card is inactive",
    [12]   = "Better contract for passenger profile exists",
    [13]   = "Contract does not match passenger profile",
    [14]   = "Max amount of aggregate value reached",
    [15]   = "Contract invalid, please contact support",
    [16]   = "Card is faulty",
    [17]   = { [0] = "Conflicting contract found on card"
    },
    [18]   = "Contract validity is longer than validity of card. Issue a new card with longer validity",
    [20]   = "Contract load action can not be cancelled. Load cancellation requirements not met",
    [21]   = "Contract load action can not be cancelled. Load cancellation requirements not met",
    [22]   = "Contract load action can not be cancelled. Contract was used after loading",
    [30]   = "The card is not the same card scanned at the beginning of the operation",
    [40]   = "Card unsupported",
    [41]   = "Connection to card abnormally disconnected",
    [43]   = "Incomplete operation detected. Please wait several minutes and try again",
    [44]   = "Request timed out. Please retry the operation",
    [50]   = "Service temporarily unavailable. Please try again later",
    [70]   = "You moved the card too fast",
    [71]   = "Cannot create conection to card",
    [72]   = "You moved the card too fast",
    [100]  = "Not possible to load more than two special passenger profiles to card. Valid special passenger profile exist, that needs to be cancelled first to be able to load more profiles",
    [101]  = "Selected passenger profile can not be loaded. You are not eligible for the selected passenger profile",
    [102]  = "Card is not prepersonalized. Prepersonalize the card at a service point",
    [1011] = "Unable to connect to the server. Please check your network connection, firewall or content blocking service settings and refresh the page",
    [1012] = "Connection blocked by the user terminal. Please check your firewall or content blocking service settings and refresh the page",
    [1013] = "Connection abnormally disconnected. Please check your network connection",
    [1014] = "App version is too old. Please update the app and try again",
    [1060] = "You moved the card too fast",
    [1061] = "You moved the card too fast",
    [1062] = "Card unsupported",
    [1070] = "Connection abnormally disconnected. Please check your internet connection"
}

--ETT_A
RAVKAV_TICKET_TYPES = {
    [1] = "Amount of rides",
    [2] = "Periodic",        --unlimited travel
    [3] = "3",
    [4] = "Free of charge",
    [5] = "5",
    [6] = "Aggregate value",
    [7] = "Amount of rides",
    [8] = "8"
}

RAVKAV_VALIDITY_TYPES = {
    [0] = "Area",
    [1] = "Tariff",
    [2] = "2",
    [3] = "Rail origin-destination",
    [4] = "4",
    [5] = "5",
    [6] = "6",
    [7] = "Rail tariff 1",
    [8] = "Rail tariff 2",
    [9] = "Predefined",
    [10] = "10",
    [11] = "11",
    [12] = "12",
    [13] = "13",
    [14] = "Rail area",
    [15] = "End of validity locations"
}

--TODO:
RAVKAV_INTERCHANGE_RIGHTS = {
---- validityBitmap 2
---- restrictionCode
---- when 1 == right to interchange until eventTime + iDuration (validityBitmap 4) (Restriction duration) in RAVKAV_INTERCHANGE_AREAS (locationBitmap 0x40 interchangesAreaId)
---- when 2 == right to continue until eventTime + iDuration == 360 (6 hours) (Restriction duration), iTrips remaining
    [1] = "Right to do transit trip until {eventTime + iDuration} in area {interchangesAreaId}",
    [2] = "Right to continue trip until {eventTime + iDuration == 360 (6 hours)}, {iTrips} remaining"
}

RAVKAV_INTERCHANGE_AREAS = {
    [0] = "Area 0",
    [1] = "Area 1 - Intercity and most areas",
    [2] = "Area 2 - Bnei Brak",
    [3] = "Area 3",
    [4] = "Area 4",
    [5] = "Area 5",
    [6] = "Area 6",
    [7] = "Area 7",
    [8] = "Area 8",
    [9] = "Area 9",
    [10] = "Area 10",
    [11] = "Area 11",
    [12] = "Area 12",
    [13] = "Area 13",
    [14] = "Area 14",
    [15] = "Area 15",
    [16] = "Area 16",
    [17] = "Area 17",
    [18] = "Area 18",
    [19] = "Area 19",
    [20] = "Area 20",
    [21] = "Area 21",
    [22] = "Area 22",
    [23] = "Area 23",
    [24] = "Area 24",
    [25] = "Area 25",
    [26] = "Area 26",
    [27] = "Area 27",
    [28] = "Area 28",
    [29] = "Area 29",
    [30] = "Area 30",
    [31] = "Area 31 - Jerusalem - Area 1 (city center + suburbs (Maale Adumim, Mevaseret Zion, Giv'at Ze'ev, etc.))",
    [32] = "Area 32",
    [33] = "Area 33 - Jerusalem - Area 3 (Beit Shemesh, Peruzdor Jerusalem)",
    [34] = "Area 34 - Jerusalem - Area 4 (Mod'in, external ring)",
    [35] = "Area 35",
    [36] = "Area 36 - Maale Adumim (part of Area 31)",
    [37] = "Area 37 - Mevaseret Zion (part of Area 31)",
    [38] = "Area 38 - Giv'at Ze'ev (part of Area 31)",
    [39] = "Area 39",
    [40] = "Area 40",
    [41] = "Area 41 - Netanya - Tayibe",
    [42] = "Area 42 - Dan Region - Ring 1 (Tel Aviv-Yafo, Ramat Gan, Giv'atayim, Bnei Brak, Petah-Tikva, Bat Yam, Holon, Rishon Le'Tziyon)",
    [43] = "Area 43 - Dan Region - Area 21 (Sharon, part of Ring 2)",
    [44] = "Area 44 - Ashdod - Gedera",
    [45] = "Area 45 - Dan Region - Petah-Tikva (part of Ring 1)",
    [46] = "Area 46 - Dan Region - Area 22 (part of Ring 2 (Rosh-Ha-Ayin)",
    [47] = "Area 47 - Hashmonaim",
    [48] = "Area 48 - Modi'in",
    [49] = "Area 49 - Highway 5",
    [50] = "Area 50",
    [51] = "Area 51 - Haifa - Center (including Isfiya and Dalit-al-Karmel)",
    [52] = "Area 52 - Krayot",
    [53] = "Area 53 - Yokneam - Tiv'on",
    [54] = "Area 54 - Rechasim",
    [55] = "Area 55 - Atlit",
    [56] = "Area 56 - HaMifrats CBS",
    [57] = "Area 57 - Hof Ha-Karmel CBS",
    [58] = "Area 58 - Nesher",
    [59] = "Area 59 - Tirat Ha-Karmel",
    [60] = "Area 60 - Akko",
    [61] = "Area 61 - Nahariya",
    [62] = "Area 62 - Carmiel",
    [63] = "Area 63 - Nazareth",
    [64] = "Area 64 - Zichron Ya'akov",
    [65] = "Area 65",
    [66] = "Area 66",
    [67] = "Area 67",
    [68] = "Area 68",
    [69] = "Area 69",
    [70] = "Area 70",
    [71] = "Area 71 - Be'er Sheva Center",
    [72] = "Area 72 - Lehavim - Rahat",
    [73] = "Area 73 - Ofakim - Hatzerim",
    [74] = "Area 74 - Meitar - Omer",
    [75] = "Area 75 - Sderot - Sha'ar HaNegev Regional Council",
    [76] = "Area 76 - Yeruham - Ramat Negev Regional Council",
    [77] = "Area 77 - Dimona - Arad",
    [78] = "Area 78 - South Mount Hevron",
    [79] = "Area 79",
    [80] = "Area 80",
    [81] = "Area 81",
    [82] = "Area 82",
    [83] = "Area 83",
    [84] = "Area 84",
    [85] = "Area 85",
    [86] = "Area 86",
    [87] = "Area 87",
    [88] = "Area 88",
    [89] = "Area 89",
    [90] = "Area 90",
    [91] = "Area 91",
    [92] = "Area 92",
    [93] = "Area 93",
    [94] = "Area 94",
    [95] = "Area 95",
    [96] = "Area 96",
    [97] = "Area 97",
    [98] = "Area 98",
    [99] = "Area 99",
    [100] = "Area 100",
    [101] = "Area 101",
    [102] = "Area 102",
    [103] = "Area 103",
    [104] = "Area 104",
    [105] = "Area 105",
    [106] = "Area 106",
    [107] = "Area 107",
    [108] = "Area 108",
    [109] = "Area 109",
    [110] = "Area 110",
    [111] = "Area 111",
    [112] = "Area 112",
    [113] = "Area 113",
    [114] = "Area 114",
    [115] = "Area 115",
    [116] = "Area 116",
    [117] = "Area 117",
    [118] = "Area 118",
    [119] = "Area 119",
    [120] = "Area 120",
    [121] = "Area 121",
    [122] = "Area 122",
    [123] = "Area 123",
    [124] = "Area 124",
    [125] = "Area 125",
    [126] = "Area 126",
    [127] = "Area 127",
    [128] = "Area 128",
    [129] = "Area 129",
    [130] = "Area 130",
    [131] = "Area 131",
    [132] = "Area 132",
    [133] = "Area 133",
    [134] = "Area 134",
    [135] = "Area 135",
    [136] = "Area 136",
    [137] = "Area 137",
    [138] = "Area 138",
    [139] = "Area 139",
    [140] = "Area 140",
    [141] = "Area 141",
    [142] = "Area 142",
    [143] = "Area 143",
    [144] = "Area 144",
    [145] = "Area 145",
    [146] = "Area 146",
    [147] = "Area 147",
    [148] = "Area 148",
    [149] = "Area 149",
    [150] = "Area 150",
    [151] = "Area 151",
    [152] = "Area 152",
    [153] = "Area 153",
    [154] = "Area 154",
    [155] = "Area 155",
    [156] = "Area 156",
    [157] = "Area 157",
    [158] = "Area 158",
    [159] = "Area 159",
    [160] = "Area 160",
    [161] = "Area 161",
    [162] = "Area 162",
    [163] = "Area 163",
    [164] = "Area 164",
    [165] = "Area 165",
    [166] = "Area 166",
    [167] = "Area 167",
    [168] = "Area 168",
    [169] = "Area 169",
    [170] = "Area 170",
    [171] = "Area 171",
    [172] = "Area 172",
    [173] = "Area 173",
    [174] = "Area 174",
    [175] = "Area 175",
    [176] = "Area 176",
    [177] = "Area 177",
    [178] = "Area 178",
    [179] = "Area 179",
    [180] = "Area 180",
    [181] = "Area 181",
    [182] = "Area 182",
    [183] = "Area 183",
    [184] = "Area 184",
    [185] = "Area 185",
    [186] = "Area 186",
    [187] = "Area 187",
    [188] = "Area 188",
    [189] = "Area 189",
    [190] = "Area 190",
    [191] = "Area 191",
    [192] = "Area 192",
    [193] = "Area 193",
    [194] = "Area 194",
    [195] = "Area 195",
    [196] = "Area 196",
    [197] = "Area 197",
    [198] = "Area 198",
    [199] = "Area 199",
    [200] = "Area 200",
    [201] = "Area 201",
    [202] = "Area 202",
    [203] = "Area 203",
    [204] = "Area 204",
    [205] = "Area 205",
    [206] = "Area 206",
    [207] = "Area 207",
    [208] = "Area 208",
    [209] = "Area 209",
    [210] = "Area 210",
    [211] = "Area 211",
    [212] = "Area 212",
    [213] = "Area 213",
    [214] = "Area 214",
    [215] = "Area 215",
    [216] = "Area 216",
    [217] = "Area 217",
    [218] = "Area 218",
    [219] = "Area 219",
    [220] = "Area 220",
    [221] = "Area 221",
    [222] = "Area 222",
    [223] = "Area 223",
    [224] = "Area 224",
    [225] = "Area 225",
    [226] = "Area 226",
    [227] = "Area 227",
    [228] = "Area 228",
    [229] = "Area 229",
    [230] = "Area 230",
    [231] = "Area 231",
    [232] = "Area 232",
    [233] = "Area 233",
    [234] = "Area 234",
    [235] = "Area 235",
    [236] = "Area 236",
    [237] = "Area 237",
    [238] = "Area 238",
    [239] = "Area 239",
    [240] = "Area 240",
    [241] = "Area 241",
    [242] = "Area 242",
    [243] = "Area 243",
    [244] = "Area 244",
    [245] = "Area 245",
    [246] = "Area 246",
    [247] = "Area 247",
    [248] = "Area 248",
    [249] = "Area 249",
    [250] = "Area 250",
    [251] = "Area 251",
    [252] = "Area 252",
    [253] = "Area 253",
    [254] = "Area 254",
    [255] = "Area 255 - No transfers"
}

RAVKAV_METROPOLIS = {
    [1]  = "Dan Region",
    [2]  = "2",
    [3]  = "3",
    [4]  = "Metropolis Be'er Sheva",
    [5]  = "Metropolis Haifa",
    [6]  = "Metropolis Jerusalem",
    [7]  = "7",
    [8]  = "8",
    [9]  = "9",
    [10] = "Outside of Metropolis"
}

-- ExtendedTicketType, ETT
--  [etta] = { [ettb] = "etta description / ettb description / comments"
--           }
RAVKAV_CONTRACT_DESCRIPTIONS = {
    [1] = { [0] = "Amount of rides / Single ride",
            [1] = "Amount of rides / Forward and return",
            [2] = "Amount of rides / Ticket for 2 trips",
            [3] = "Amount of rides / Ticket for 5 trips",
            [4] = "Amount of rides / Ticket for 10 trips",
            [5] = "Amount of rides / Ticket for 12 trips / Israel Railways only",
            [6] = "Amount of rides / Ticket for 15 trips",
            [7] = "Amount of rides / Ticket for 20 trips"
          },
    [2] = { [0] = "Periodic / Month unlimited travel",
            [1] = "Periodic / Week unlimited travel",
            [2] = "Periodic / Day unlimited travel",
            [3] = "Periodic / Semester B unlimited travel",
            [4] = "Periodic / Semester A unlimited travel",
            [5] = "Periodic / Annual unlimited travel"
          },
    [4] = { [0] = "Free of charge / Reserve soldier coupon",
            [1] = "Free of charge / Special travel",
            [2] = "Free of charge / Special travel / (soldiers only)"
          },
    [6] = { [0] = "Aggregate value / Value 1 / Payment of NIS 30",
            [1] = "Aggregate value / Value 2 / Payment of NIS 50",
            [2] = "Aggregate value / Value 3 / Payment of NIS 100",
            [3] = "Aggregate value / Value 4 / Payment of NIS 150",
            [4] = "Aggregate value / Value 5 / Payment of NIS 200",
            [5] = "Aggregate value / Value 6 / Payment of NIS 5 + 30 (Dan Region)",
            [6] = "Aggregate value / Dan Region / Payment of NIS 5 + 13.20",
            [7] = "Aggregate value / Dan Region / Payment of NIS 5 + 20.80"
          },
    [7] = { [0] = "Amount of rides / Rides 4 / Ticket for 4 trips",
            [1] = "Amount of rides / Rides 6 / Ticket for 6 trips",
            [2] = "Amount of rides / Supplement ticket/voucher to claim / addition to existing ticket",
            [3] = "Amount of rides / More than 20 rides / Special ride tickets"
          }
}

--Predefined contract IDs
--   0- 999 Reserved by MOT
--1000-1999 Egged
--2000-2047 Compatibility tests
RAVKAV_CONTRACT_TYPES = {
    --code = description / operators / comments
    [1] = "[Free travel] \"Rest of the country\" - entire country except for Arava / [all] / (soldiers)",
    [2] = "[Free travel] Arava / [Eilot District, Egged] / (soldiers)",
    [3] = "[Free travel] / [all, private for each] / (operator employees and family)",
    [4] = "[Free travel] Dan Region",
    [5] = "[Free travel] Modi'in",
    [6] = "[Free travel] Entire country except for Arava starting from fare code 5 and up",
    [7] = "[Free travel] Entire country up to fare code 7 inclusive",
    [8] = "[Free travel] Jerusalem Light Rail / [CityPass] / (police, inspectors)",
    [9] = "[Free travel] Egged + Egged Transport / [Egged, Egged Transport] / (operator employees and family)",
    [10] = "[Free travel] Dan + Kavim [Dan, Kavim] / (operator employees and family)",
    [11] = "[Free travel] Dan + Kavim + Egged / [Dan, Kavim, Egged] / (operator employees and family)",
    [12] = "[Free travel] Dan + Egged / [Dan, Egged] / (operator employees and family)",
    [13] = "[Free travel] Golan Heights Youth Student Pass / [Golan Heights Regional Council] / (from September 1, 2011)",
    [14] = "[Free travel] Netanya Municipality Youth / [Egged Transport]",
    [15] = "Month pass: Beitar Illit <> Beit Shemesh / [Kavim]",
    [16] = "Month pass: Beitar Illit only / [Kavim]",
    [17] = "Month pass: Beitar Illit only youth / [Kavim] / (youth only, discount excepted)",
    [18] = "[Free travel] Youth student pass: Shoham / Modi'in Illit / [Superbus] / (youth only)",
    [19] = "Month pass: Beitar Illit <> Beit Shemesh youth / [Kavim] / (youth only, discount excepted)",
    [20] = "Youth student pass: Shoham Extended / [Superbus] / (youth only)",
    [21] = "Month pass: Beit Shemesh only / [Superbus] / (standard, standard student included)",
    [22] = "Month pass: Modi'in Illit only / [Kavim, Superbus]",
    [23] = "Month pass: Ramla only / [Kavim, Superbus]",
    [24] = "Month pass: Modi'in Illit <> Bnei Brak / [Superbus]",
    [25] = "Month pass: Shoham <> Tel-Aviv / [Superbus]",
    [26] = "Month pass: Shoham <> Ben-Gurion Airport / [Superbus]",
    [27] = "Month pass: Modi'in only / [Kavim]",
    [28] = "Month pass: Modi'in <> Ramla <> Lod / [Kavim]",
    [29] = "Month pass: Modi'in <> Tel-Aviv / [Connex Veolia]",
    [30] = "Month pass: Modi'in <> Jerusalem / [Connex Veolia]",
    [31] = "Month pass: Ashdod regional / [Afikim, Connex Veolia]",
    [32] = "Month pass: Yavne / [Afikim, Connex Veolia]",
    [33] = "Week pass: Ashdod regional / [Connex Veolia]",
    [34] = "Semester pass: Modi'in <> Jerusalem / [Connex Veolia] / (students only)",
    [35] = "Annual pass: Modi'in <> Jerusalem / [Connex Veolia] / (students only)",
    [36] = "Day pass: Ramla / [Kavim]",
    [37] = "Day pass: Lod / [Kavim]",
    [38] = "Student pass: Shoham <> Petah-Tikva / [Superbus] / (youth only)",
    [39] = "Day pass: Lod <> Tel-Aviv / [Connex Veolia]",
    [41] = "Semester pass: Modi'in <> Tel-Aviv / [Connex Veolia] / (students only)",
    [42] = "Annual pass: Modi'in <> Tel-Aviv / [Connex Veolia] / (students only)",
    [45] = "Month pass: Rahat urban / [Galim (Narkis Gal)]",
    [46] = "Month pass: Rahat extended / [Galim (Narkis Gal)]",
    [51] = "Semester pass: Kiryat-Gat / [Egged Transport] / (students only)",
    [52] = "Annual pass: Kiryat-Gat / [Egged Transport] / (students only)",
    [53] = "Semester pass: Ashkelon <> Kiryat-Gat / [Egged Transport] / (students only)",
    [54] = "Annual pass: Ashkelon <> Kiryat-Gat / [Egged Transport] / (students only)",
    [55] = "Day pass: Ashdod only / [Afikim]",
    [56] = "Month pass: Ashdod only / [Afikim]",
    [57] = "Month pass: Ashkelon / [Egged Transport]",
    [58] = "Month pass: Kiryat-Gat / [Egged Transport]",
    [59] = "Month pass: Ashkelon <> Kiryat-Gat / [Egged Transport]",
    [60] = "Month pass: Be'er Sheva urban / [Metrodan]",
    [61] = "Semester pass: Student / [Egged Transport] / (Netanya, Ashdod, Ashkelon, students only)",
    [62] = "Annual pass: Student / [Egged Transport] / (Netanya, Ashdod, Ashkelon, students only)",
    [63] = "Week pass: Nazareth <> Kfar Kana / [GB Tours]",
    [64] = "Week pass: Nazareth <> Turan/Baina / [GB Tours]",
    [68] = "Week pass: Turan <> Haifa / [GB Tours]",
    [69] = "Annual pass: lines 28, 298, 299 / [Travel and Tourism] / (students only)",
    [70] = "Month pass: Afula / [Superbus, Kavim] / (standard, standard student included)",
    [71] = "Day pass: Afula / [Superbus, Kavim]",
    [72] = "Day pass: Ha'Emek - Extended / [Superbus, Kavim]",
    [73] = "Day pass: Mount Tabor / [Superbus, Kavim]",
    [74] = "Day pass: Tiberias / [Connex Veolia]",
    [75] = "Month pass: Tiberias / [Superbus, Connex Veolia] / (standard, standard student included)",
    [76] = "Week pass: Ma'alot <> Kfar Yasif <> Nahariya / [Nativ Express]",
    [77] = "Month pass: Nazareth / [United Bus Services Nazareth]",
    [78] = "Month pass: Nazareth <> Kfar Kana / [United Bus Services Nazareth]",
    [79] = "Week pass: Peki'in <> Horfish <> Nahariya / [Nativ Express]",
    [81] = "Month pass: Netanya only / [Egged Transport]",
    [82] = "Day pass: Netanya only / [Egged Transport]",
    [85] = "Month pass: Migdal HaEmek [Superbus] / (standard, standard student included)",
    [86] = "Month pass: Safed / [Nativ Express]",
    [87] = "Month pass: Nahariya / [Nativ Express]",
    [88] = "Month pass: Shlomi <> Nahariya / [Nativ Express]",
    [91] = "Day pass: Dan Region: Petah-Tikva and Rosh Ha'Ayin - Purple / [Kavim, Afikim]",
    [92] = "Month pass: Elad <> Petah-Tikva / [Kavim]",
    [93] = "Month/Day pass: Elad <> Bnei Brak / [Kavim]",
    [94] = "Day pass: Elad / [Kavim]",
    [95] = "Week pass: Or Akiva <> Hadera / [Nativ Express, Kavim]",
    [96] = "Week pass: Jat <> Harish <> Hadera / [Nativ Express, Kavim]",
    [97] = "Month pass: Kadima/Zoran <> Netanya / [Nativ Express]",
    [98] = "Month pass: Netanya <> Tel-Aviv / [Nativ Express]",
    [100] = "Month pass: Dan Region - White / [Egged, Dan, Kavim, Metropoline, Afikim] / (sold through Afikim/Kavim only, including student contracts)",
    [101] = "[Free / Special travel] - Tel Aviv University",
    [105] = "Month pass: Dan Region - Brown - Gush 5 - Samaria / [Egged, Dan, Kavim, Metropoline, Afikim] / (sold through Afikim only, including student contracts)",
    [109] = "Month pass: Dan Region - Purple - Petah-Tikva and Rosh Ha'Ayin [Kavim, Afikim]",
    [111] = "Month pass: Dan Region - Zone 1 / [Dan, Egged, Kavim, Metropoline] / (including students)",
    [112] = "Month pass: Dan Region - Zone 2 / [Dan, Egged, Kavim, Metropoline] / (including students)",
    [113] = "Month pass: Dan Region - Extended / [Dan, Egged, Kavim, Metropoline] / (including students)",
    [120] = "Day pass: Dan Region - special / [Dan] / (in place of damaged smartcard)",
    [121] = "Dan Region - Amount of rides - code 41 / [Dan, Egged, Kavim, Metropoline] / (ring 2, zone 22 + Petah-Tikva only)",
    [122] = "Dan Region - Amount of rides - code 42 / [Dan, Egged, Kavim, Metropoline] / (ring 1 only)",
    [123] = "Dan Region - Amount of rides - code 43 / [Dan, Egged, Kavim, Metropoline] / (ring 2, zone 21 only)",
    [124] = "Dan Region - Amount of rides - code 44 / [Dan, Egged, Kavim, Metropoline] / (extended)",
    [135] = "Day pass: Dan Region - Ring 1 / [Dan, Egged, Kavim, Metropoline] / (includes Petah-Tikva area)",
    [137] = "Month pass: Dan Region - Gray - Bnei Brak / [Dan]",
    [141] = "Month/Week/Day pass: Dan Region - Ring 1 / [Dan, Egged, Kavim, Metropoline, Afikim, Nativ Express, Israel Railways]",
    [142] = "Month/Week/Day pass: Dan Region - Extended - Ring 1, 2.1, 2.2, 2.3 / [Dan, Egged, Egged Transport, Kavim, Metropoline, Afikim, Nativ Express, Israel Railways]",
    [143] = "Month/Week/Day pass: Dan Region + North - Ring 1, 2.1, 2.2, 3.1, 3.4 / [Dan, Egged, Egged Transport, Kavim, Metropoline, Afikim, Nativ Express, Israel Railways]",
    [144] = "Month/Week/Day pass: Dan Region + South - Ring 1, 2.2, 2.3, 3.2, 3.3 / [Dan, Egged, Egged Transport, Kavim, Metropoline, Afikim, Nativ Express, Israel Railways]",
    [145] = "Month/Week/Day pass: Dan Region: HaSharon + Netanya - Ring 2.1, 3.1, 3.4 / [Dan, Egged, Egged Transport, Kavim, Metropoline, Afikim, Nativ Express, Israel Railways]",
    [146] = "Month/Week/Day pass: Dan Region: Metropolis East - Ring 2.2, 3.2, 3.4 / [Dan, Egged, Egged Transport, Kavim, Metropoline, Afikim, Israel Railways]",
    [147] = "Month/Week/Day pass: Dan Region: Metropolis South - Ring 2.3, 3.2, 3.3 / [Dan, Egged, Egged Transport, Kavim, Metropoline, Afikim, Israel Railways]",
    [148] = "Month/Week/Day pass: FULL Dan Region - Ring 1, 2.1, 2.2, 2.3, 3.1, 3.2, 3.3, 3.4 / [Dan, Egged, Egged Transport, Kavim, Metropoline, Afikim, Nativ Express, Israel Railways]",
    [150] = "Month/Week/Day pass: FULL Dan Region + Hadera - Ring 1, 2.1, 2.2, 2.3, 3.1, 3.2, 3.3, zone 701, 702 / [Dan, Egged, Egged Transport, Kavim, Metropoline, Afikim, Nativ Express, Superbus, Israel Railways] / (excluding ring 3.4)",
    [151] = "Month/Week/Day pass: FULL Dan Region + Ashkelon - Ring 1, 2.1, 2.2, 2.3, 3.1, 3.2, 3.3, 3.4, zone 801, 802 / [Dan, Egged, Egged Transport, Kavim, Metropoline, Afikim, Nativ Express, Israel Railways]",
    [152] = "Month/Week/Day pass: Dan Region: HaSharon region only - Ring 2.1 / [Dan, Egged, Kavim, Metropoline, Nativ Express, Israel Railways]",
    [153] = "Month/Week/Day pass: Dan Region: Rosh-Ha-Ayin + Shoham region only - Ring 2.2 / [Egged, Egged Transport, Kavim, Metropoline, Afikim, Israel Railways]",
    [154] = "Month/Week/Day pass: Dan Region: Rehovot region only - Ring 2.3 / [Egged, Kavim, Metropoline, Afikim, Israel Railways]",
    [155] = "Month/Week/Day pass: Dan Region: Netanya region only - Ring 3.1 / [Egged, Egged Transport, Kavim, Metropoline, Nativ Express, Israel Railways]",
    [156] = "Month/Week/Day pass: Dan Region: Modi'in region only - Ring 3.2 / [Egged, Egged Transport, Kavim, Metropoline, Nativ Express, Israel Railways]",
    [157] = "Month/Day pass: Dan Region: Ashdod region only - Ring 3.3 / [Dan South, Afikim, Egged, Egged Transport, Kavim, Metropoline, Israel Railways]",
    [171] = "Month/Week/Day pass: Metropolis Be'er Sheva: Be'er Sheva - Ring 1 / [Dan Be'er Sheva, Dan South, Egged, Egged Transport, Metrodan, Metropoline, Israel Railways]",
    [172] = "Month/Week/Day pass: Metropolis Be'er Sheva: Be'er Sheva - Extended - Ring 1, 2.1, 2.2, 2.3 / [Dan Be'er Sheva, Dan South, Egged, Egged Transport, Metropoline, Metrodan, Israel Railways]",
    [173] = "Month/Week/Day pass: Metropolis Be'er Sheva: Be'er Sheva and Western Negev - Ring 1, 2.1, 2.2, 3.1, 3.2 / [Dan Be'er Sheva, Dan South, Egged, Egged Transport, Metropoline, Metrodan, Israel Railways]",
    [174] = "Month/Week/Day pass: Metropolis Be'er Sheva: Be'er Sheva + South East - Ring 1, 2.1, 2.3, 3.2, 3.3, 3.4 / [Dan Be'er Sheva, Dan South, Egged, Egged Transport, Metrodan, Metropoline, Israel Railways]",
    [175] = "Month/Week/Day pass: Metropolis Be'er Sheva: West area + Negev - Ring 2.1, 2.2, 3.1, 3.2 / [Dan South, Egged, Egged Transport, Metropoline, Israel Railways]",
    [176] = "Month/Week/Day pass: Metropolis Be'er Sheva: Lehavim area + West area + Negev - Ring 2.1, 2.2, 3.2, 3.3, 3.4 / [Dan South, Egged, Egged Transport, Metropoline, Israel Railways]",
    [177] = "Month/Week/Day pass: FULL Metropolis Be'er Sheva + Mitzpe Ramon area - Ring 1, 2.1, 2.2, 2.3, 3.1, 3.2, 3.3, 3.4 + zone 811/901 / [Dan Be'er Sheva, Dan South, Egged, Egged Transport, Metropoline, Metrodan, Israel Railways]",
    [178] = "Month pass: FULL Metropolis Be'er Sheva + Ashkelon area - Ring 1, 2.1, 2.2, 2.3, 3.1, 3.2, 3.3, 3.4 + zone 801, 802 / [Dan Be'er Sheva, Dan South, Egged, Egged Transport, Metropoline, Metrodan, Israel Railways]",
    [179] = "Month/Week/Day pass: FULL Metropolis Be'er Sheva + Ashkelon area - Ring 1, 2.1, 2.2, 2.3, 3.1, 3.2, 3.3, 3.4 + zone 801, 802 / [Dan Be'er Sheva, Dan South, Egged, Egged Transport, Metropoline, Metrodan, Israel Railways]",
    [180] = "Month/Week/Day pass: Metropolis Be'er Sheva: Rahat + Lehavim area only - Ring 2.1 / [Dan South, Egged, Egged Transport, Metropoline, Israel Railways]",
    [181] = "Month/Week/Day pass: Metropolis Be'er Sheva: Ofakim area only - Ring 2.2 / [Dan South, Egged, Egged Transport, Metropoline, Israel Railways]",
    [182] = "Month/Week/Day pass: Metropolis Be'er Sheva: Omer + Hura area only - Ring 2.3 / [Egged, Egged Transport, Metropoline, Israel Railways]",
    [183] = "Month/Week/Day pass: Metropolis Be'er Sheva: Sderot + Netivot area only - Ring 3.1 / [Dan South, Egged, Egged Transport, Metropoline, Israel Railways]",
    [184] = "Month/Week/Day pass: Metropolis Be'er Sheva: Yeruham area only - Ring 3.2 / [Egged, Metropoline]",
    [185] = "Month/Week/Day pass: Metropolis Be'er Sheva: Arad + Dimona area only - Ring 3.3 / [Egged, Egged Transport, Metropoline, Israel Railways]",
    [186] = "Month/Week/Day pass: Metropolis Be'er Sheva: Southern Mt Hevron area only - Ring 3.4 / [Egged, Egged Transport, Metropoline]",
    [200] = "Nationwide aggregate value",
    [210] = "Elad aggregate value / [Egged Transport] / (Elad cluster only)",
    [220] = "Afula aggregate value / [Kavim] / (HaEmek cluster only)",
    [225] = "Hashmonaim aggregate value / [Kavim] / (Hashmonaim cluster only)",
    [300] = "Sharing agreement - lines 31, 332 / [Travel and Tourism, GB Tours] / (all shared contracts)",
    [301] = "Sharing agreement - code 1 / [Travel and Tourism, GB Tours] / (all shared contracts)",
    [303] = "Sharing agreement - code 3 / [Travel and Tourism, GB Tours] / (all shared contracts)",
    [304] = "Sharing agreement - code 4 / [Travel and Tourism, GB Tours] / (all shared contracts)",
    [305] = "Sharing agreement - code 5 / [Travel and Tourism, GB Tours] / (all shared contracts)",
    [306] = "Sharing agreement - code 6 / [Travel and Tourism, GB Tours] / (all shared contracts)",
    [307] = "Sharing agreement - code 7 (including week pass) / [Travel and Tourism, GB Tours] / (all shared contracts)",
    [308] = "Sharing agreement - code 8 (including week pass and students) / [Travel and Tourism, GB Tours] / (all shared contracts)",
    [309] = "Sharing agreement - code 9 / [Travel and Tourism, GB Tours] / (all shared contracts)",
    [311] = "Sharing agreement - code 11 (including week pass and students) / [Travel and Tourism, GB Tours] / (all shared contracts)",
    [312] = "Sharing agreement - code 52 / [Travel and Tourism, GB Tours] / (all shared contracts)",
    [313] = "Sharing agreement - code 63 / [Travel and Tourism, GB Tours] / (all shared contracts)",
    [326] = "Continuation of trip - code 6 / [Travel and Tourism, GB Tours, Egged]",
    [327] = "Continuation of trip - code 7 / [Travel and Tourism, GB Tours, Egged]",
    [328] = "Continuation of trip - code 8 / [Travel and Tourism, GB Tours, Egged]",
    [341] = "Month pass: Tamra / [Egged, Nativ Express]",
    [345] = "Month pass: Umm al-Fahm / [Kavim]",
    [346] = "Month pass: Elad / [Kavim]",
    [348] = "Month pass: Dimona / [Egged]",
    [349] = "Annual/Semester B pass: / [Dan South] / (standard students)",
    [351] = "Month pass: Baqa al-Gharbiyye / [Kavim]",
    [352] = "Annual/Semester B pass: / [Dan South] / (standard students)",
    [353] = "Month pass: Arad / [Metropoline]",
    [354] = "Annual/Semester B pass: / [Dan South] / (standard students)",
    [355] = "Annual/Semester B pass: / [Dan South] / (standard students)",
    [356] = "Month pass: Ariel / [Afikim]",
    [357] = "Month pass: Beit She'an / [Superbus, Kavim] / (standard, standard student included)",
    [365] = "Week pass: Migdal Ha'Emek <> Haifa / [Travel and Tourism, GB Tours]",
    [366] = "Week pass: Nazareth / Nazareth Illit <> Haifa / [Travel and Tourism, GB Tours]",
    [367] = "Week pass: Nazareth <> University / [Travel and Tourism, GB Tours]",
    [499] = "Month/Week/Day pass: Metropolis Haifa: Hadera <> Haifa (including Wadi Ara, Afula, Beit She'an areas) - Ring 1, 2.1, 2.2, 3.1, 3.2, 3.3, 3.4, zone 601, 602, 701, 702 / [Egged, Dan North, Carmelit, Kavim, Superbus, Israel Railways]",
    [500] = "Month/Week/Day pass: Metropolis Haifa: Circular Haifa - Ring 1 / [Egged, Dan North, Carmelit, Nativ Express, Kavim, Superbus, Israel Railways]",
    [501] = "Month/Week/Day pass: Metropolis Haifa: Circular Haifa - Extended - Ring 1, 2.1, 2.2 / [Egged, Dan North, Carmelit, Nativ Express, Kavim, Superbus, Israel Railways]",
    [502] = "Month/Week/Day pass: Metropolis Haifa: Circular Haifa - Northern - Ring 1, 2.1, 3.1, 3.2 / [Egged, Dan North, Carmelit, Nativ Express, Kavim, Superbus, Israel Railways]",
    [503] = "Month/Week/Day pass: Metropolis Haifa: Circular Haifa - Southern - Ring 1, 2.2, 3.3, 3.4 / [Egged, Dan North, Carmelit, Nativ Express, Kavim, Superbus, Israel Railways]",
    [504] = "Month/Week/Day pass: Metropolis Haifa: Northern - Ring 2.1, 3.1, 3.2 / [Egged, Nativ Express, Kavim, Superbus, Israel Railways]",
    [505] = "Month/Week/Day pass: Metropolis Haifa: Southern - Ring 2.2, 3.3, 3.4 / [Egged, Nativ Express, Kavim, Superbus, Israel Railways]",
    [506] = "Month/Week/Day pass: Metropolis Haifa: Eastern - Ring 2.1, 2.2, 3.2, 3.3 / [Egged, Nativ Express, Kavim, Superbus, Israel Railways]",
    [510] = "Month pass: Netanya / [Egged Transport, Nativ Express] / (sold by Egged Transport)",
    [511] = "Month pass: Netanya <> Kfar Yona / [Egged Transport, Nativ Express] / (sold by Nativ Express)",
    [512] = "Month pass: Netanya <> Tel-Aviv / [Egged Transport, Nativ Express] / (sold by Nativ Express)",
    [515] = "Month pass: Hadera / [Egged, Nativ Express]",
    [516] = "Month pass: Hadera <> Or Akiva / [Egged, Nativ Express]",
    [517] = "Month pass: Hadera <> Pardes Hana / [Egged, Nativ Express]",
    [518] = "Month pass: Netanya <> Hadera / [Egged, Egged Transport, Nativ Express, Kavim]",
    [520] = "Month pass: Metropolis Haifa / [Egged, Nativ Express]",
    [521] = "Single ride - code 10 / [Egged, Nativ Express]",
    [522] = "Single ride - code 2 / [Egged, Nativ Express]",
    [524] = "Single ride - code 4 / [Egged, Nativ Express]",
    [526] = "Single ride - code 6 / [Egged, Nativ Express]",
    [527] = "Single ride - code 7 / [Egged, Nativ Express]",
    [528] = "Single ride - code 8 / [Egged, Nativ Express]",
    [529] = "Single ride - code 9 / [Egged, Nativ Express]",
    [530] = "Month pass: Haifa zone / [Egged, Nativ Express]",
    [532] = "Month pass: Haifa extended / [Egged, Nativ Express]",
    [534] = "Semester pass: Afula <> Haifa / [Egged, Nativ Express] / (students only)",
    [535] = "Annual pass: Afula <> Haifa / [Egged, Nativ Express] / (students only)",
    [536] = "Semester pass: Metropolis Haifa / [Egged, Nativ Express] / (students only)",
    [537] = "Annual pass: Metropolis Haifa / [Egged, Nativ Express] / (students only)",
    [538] = "Semester pass: Haifa zone / [Egged, Nativ Express] / (students only)",
    [539] = "Annual pass: Haifa zone / [Egged, Nativ Express] / (students only)",
    [540] = "Continuation of trips - intercity lines / [Egged, Dan North]",
    [541] = "Amount of rides - code 10 / [Egged, Nativ Express]",
    [542] = "Amount of rides - code 2 / [Egged, Nativ Express]",
    [544] = "Amount of rides - code 4 / [Egged, Nativ Express]",
    [545] = "Amount of rides - code 6 - with hourly transfers / [Egged, Nativ Express]",
    [546] = "Amount of rides - code 6 - without hourly transfers / [Egged, Nativ Express]",
    [547] = "Amount of rides - code 7 / [Egged, Nativ Express]",
    [548] = "Amount of rides - code 8 / [Egged, Nativ Express]",
    [549] = "Amount of rides - code 9 / [Egged, Nativ Express]",
    [550] = "Month pass: Krayot area / [Egged, Dan North]",
    [551] = "Month pass: Nahariya <> Akko / [Egged, Nativ Express]",
    [552] = "Month pass: Nahariya <> Kiryat Ata Junction / [Egged, Nativ Express]",
    [553] = "Month pass: Nahariya <> Akko <> Haifa / [Egged, Nativ Express]",
    [554] = "Month pass: Carmiel <> Akko / [Egged, Nativ Express]",
    [558] = "Month pass: Akko <> Haifa / [Egged, Nativ Express]",
    [560] = "Month/Week/Day pass: Metropolis Haifa: Akko area only - Ring 2.1 / [Egged, Nativ Express, Israel Railways]",
    [561] = "Month/Week/Day pass: Metropolis Haifa: Yokneam - Tiv'on area only - Ring 2.2 / [Egged, Nativ Express, Kavim, Superbus, Israel Railways]",
    [562] = "Month/Week/Day pass: Metropolis Haifa: Nahariya area only - Ring 3.1 / [Egged, Nativ Express, Superbus, Israel Railways]",
    [563] = "Month/Week/Day pass: Metropolis Haifa: Carmiel area only - Ring 3.2 / [Egged, Nativ Express, Superbus]", --overlap 1007
    [564] = "Month/Week/Day pass: Metropolis Haifa: Nazareth area only - Ring 3.3 / [Egged, Nativ Express, Superbus]",
    [565] = "Month/Week/Day pass: Metropolis Haifa: Zichron area only - Ring 3.4 / [Egged, Nativ Express, Kavim, Superbus, Israel Railways]",
    [602] = "Single ride - Jerusalem extended - code 2 + continuation / [Egged, Superbus, Egged Transport]",
    [603] = "Single ride - Peruzdor <> Jerusalem - code 3 + continuation / [Egged, Superbus, Egged Transport]",
    [604] = "Amount of rides - Jerusalem extended - code 2 + continuation / [Egged, Superbus, Egged Transport]",
    [605] = "Amount of rides - Peruzdor <> Jerusalem - code 5 + continuation / [Egged, Superbus, Egged Transport]",
    [606] = "Amount of rides - Peruzdor <> Jerusalem - code 6 + continuation / [Egged, Superbus, Egged Transport]",
    [607] = "Amount of 2 rides - Beitar Illit <> Jerusalem + continuation / [Egged, Kavim]",
    [608] = "Amount of 10 rides - Beitar Illit <> Jerusalem + continuation / [Egged, Kavim] / (eligible for Social Security only (not including youth / senior citizen))",
    [609] = "Amount of 5 rides - Beitar Illit <> Jerusalem + continuation / [Egged, Kavim]",
    [610] = "Amount of 10 rides - Beitar Illit <> Jerusalem + continuation / [Egged, Kavim] / (youth/senior citizen only)",
    [611] = "Annual pass: Beitar Illit - extended student / [Egged, Kavim, Egged Transport, CityPass] / (students only)",
    [612] = "Semester A pass: Beitar Illit - extended student / [Egged, Kavim, Egged Transport, CityPass] / (students only)",
    [613] = "Semester B pass: Beitar Illit - extended student / [Egged, Kavim, Egged Transport, CityPass] / (students only)",
    [614] = "Annual pass: Beitar Illit - standard student / [Egged, Kavim, Egged Transport, CityPass] / (students only)",
    [615] = "Semester A pass: Beitar Illit - standard student [Egged, Kavim, Egged Transport, CityPass] / (students only)",
    [616] = "Semester B pass: Beitar Illit - standard student [Egged, Kavim, Egged Transport, CityPass] / (students only)",
    [617] = "Amount of 2 rides (Forward and return) + continuation / [Egged, Kavim] / (youth / senior citizen only)",
    [620] = "Annual pass: Beit Shemesh neighborhood <> Jerusalem - standard student / [Egged, Superbus, CityPass, Egged Transport] / (students only)",
    [621] = "Annual pass: Peruzdor <> Jerusalem - standard student / [Egged, Superbus, CityPass, Egged Transport] / (students only)",
    [622] = "Semester A pass: Beit Shemesh neighborhood <> Jerusalem - standard student / [Egged, Superbus, CityPass, Egged Transport] / (students only)",
    [623] = "Semester A pass: Peruzdor <> Jerusalem - standard student / [Egged, Superbus, CityPass, Egged Transport] / (students only)",
    [624] = "Semester B pass: Beit Shemesh neighborhood <> Jerusalem - standard student / [Egged, Superbus, CityPass, Egged Transport] / (students only)",
    [625] = "Semester B pass: Peruzdor <> Jerusalem - standard student / [Egged, Superbus, CityPass, Egged Transport] / (students only)",
    [626] = "Annual pass: Modi'in Illit <> Jerusalem - standard student / [Egged, Superbus, CityPass, Egged Transport] / (students only)",
    [627] = "Semester A pass: Modi'in Illit <> Jerusalem - standard student / [Egged, Superbus, CityPass, Egged Transport] / (students only)",
    [628] = "Semester B pass: Modi'in Illit <> Jerusalem - standard student / [Egged, Superbus, CityPass, Egged Transport] / (students only)",
    [629] = "Month pass: Jerusalem <> Shapirim [Egged Transport]",
    [632] = "Month pass: Beit Shemesh <> Jerusalem / [Egged, Superbus, CityPass, Egged Transport] / (sold by Superbus)",
    [633] = "Month pass: Peruzdor <> Jerusalem / [Egged, Superbus, CityPass, Egged Transport] / (sold by Superbus)",
    [634] = "Month pass: Modi'in Illit <> Jerusalem / [Egged, Superbus, CityPass, Egged Transport] / (sold by Superbus)",
    [636] = "Month pass: Beitar Illit extended youth / [Egged, Kavim, Egged Transport, CityPass] / (sold by Kavim)",
    [637] = "Month pass: Extended - Beitar Illit <> Jerusalem / [Egged, Kavim, Egged Transport, CityPass] / (sold by Kavim)",
    [638] = "Month pass: Standard - Beitar Illit <> Jerusalem / [Egged, Kavim, Egged Transport, CityPass] / (sold by Kavim)",
    [641] = "Single ride - Jerusalem shared - code 2 / [Egged, CityPass, Egged Transport]",
    [642] = "Single ride - Jerusalem shared - code 3 / [Egged, CityPass, Egged Transport]",
    [645] = "Amount of rides - Jerusalem shared - code 2 / [Egged, CityPass, Egged Transport]",
    [646] = "Amount of rides - Jerusalem shared - code 3 / [Egged, CityPass, Egged Transport]",
    [647] = "Amount of 2 rides - Jerusalem / [Egged, CityPass, Egged Transport]",
    [651] = "Semester A pass: Jerusalem extended / [Egged, CityPass, Superbus] / (students only)",
    [652] = "Annual pass: Jerusalem extended / [Egged, CityPass, Superbus] / (students only)",
    [653] = "Month pass: Jerusalem extended / [Egged, CityPass, Superbus] / (valid on Superbus only)",
    [654] = "Semester B pass: Jerusalem extended / [Egged, CityPass, Superbus] / (students only)",
    [656] = "Annual pass: Beit Shemesh <> Jerusalem / [Egged, CityPass, Egged Transport] / (students only)",
    [657] = "Semester A pass: Beit Shemesh <> Jerusalem / [Egged, CityPass, Egged Transport] / (students only)",
    [658] = "Semester B pass: Beit Shemesh <> Jerusalem / [Egged, CityPass, Egged Transport] / (students only)",
    [659] = "Month pass: Beit Shemesh Jerusalem / [Egged, CityPass, Egged Transport]",
    [671] = "Month/Week/Day pass: Metropolis Jerusalem - Circular Jerusalem - Ring 1 / [Egged, Egged Transport, Superbus, CityPass, Israel Railways]",
    [672] = "Month/Week/Day pass: Metropolis Jerusalem - Circular Jerusalem Extended - Ring 1, 2.1, 2.2, 2.3 / [Egged, Egged Transport, Kavim, Superbus, CityPass, Israel Railways]",
    [673] = "Month/Week/Day pass: Metropolis Jerusalem - Circular Jerusalem + West - Ring 1, 2.1, 3.1, 3.2, 3.5 / [Egged, Egged Transport, Kavim, Superbus, Afikim, CityPass, Israel Railways]",
    [674] = "Month/Week/Day pass: Metropolis Jerusalem - Circular Jerusalem + East - Ring 1, 2.2, 2.3, 3.3, 3.4, 3.5 / [Egged, Egged Transport, Superbus, Afikim, CityPass]",
    [675] = "Month/Week/Day pass: Metropolis Jerusalem: West - Ring 2.1, 3.1, 3.2, 3.5 / [Egged, Egged Transport, Superbus, Kavim, Afikim, Israel Railways]",
    [676] = "Month/Week/Day pass: Metropolis Jerusalem: East - Ring 2.2, 2.3, 3.3, 3.4, 3.5 / [Egged, Egged Transport]",
    [677] = "Month/Week/Day pass: FULL Metropolis Jerusalem - Ring 1, 2.1, 2.2, 2.3, 3.1, 3.2, 3.3, 3.4, 3.5 / [Egged, Egged Transport, Kavim, Superbus, Afikim, CityPass, Israel Railways]",
    [680] = "Lines 400-402 Bnei Brak <> Jerusalem / [Egged, Connex]",
    [690] = "Month pass: East Jerusalem / [East Jerusalem operators]",
    [692] = "Month pass: East Jerusalem extended / [East Jerusalem operators]",
    [693] = "Month/Week/Day pass: Metropolis Jerusalem: Jerusalem Mountains - Ring 2.1 / [Egged, Kavim, Superbus, Afikim]",
    [694] = "Month/Week/Day pass: Metropolis Jerusalem: Binyamin area only - Ring 2.2 / [Egged, Egged Transport]",
    [695] = "Month/Week/Day pass: Metropolis Jerusalem: Gush Etsion area only - Ring 2.3 / [Egged, Egged Transport]",
    [696] = "Month/Week/Day pass: Metropolis Jerusalem: Beit Shemesh area only - Ring 3.1 / [Egged, Kavim, Superbus, Afikim, Israel Railways]",
    [697] = "Month/Week/Day pass: Metropolis Jerusalem: Hebel Modi'in area only - Ring 3.2 / [Egged, Egged Transport, Kavim, Superbus, Israel Railways]",
    [698] = "Month/Week/Day pass: Metropolis Jerusalem: Dead Sea Valley area only - Ring 3.3 / [Egged, Egged Transport]",
    [699] = "Month/Week/Day pass: Metropolis Jerusalem: Kiryat Arba area only - Ring 3.4 / [Egged, Egged Transport]",
    [701] = "Month pass: Ramla <> Lod / [Egged, Superbus, Kavim]",
    [702] = "Month pass: Be'er Ya'akov <> Ben-Gurion Airport / [Egged, Superbus, Connex]",
    [703] = "Month pass: Ramla <> Lod <> Tel-Aviv / [Egged, Superbus, Connex]",
    [704] = "Month pass: Rehovot <> Rishon Le'Tziyon <> Ramla <> Lod / [Egged, Superbus, Connex]",
    [705] = "Month pass: Lod urban / [Egged, Superbus, Kavim]",
    [706] = "Month pass: Lod <> Petah-Tikva / [Egged, Connex]",
    [707] = "Month pass: Rehovot <> Rishon Le'Tziyon Be'er Ya'akov junction / [Egged, Superbus]",
    [708] = "Semester B pass: Rehovot <> Tel-Aviv / [Egged, Superbus] / (students only, not valid for 5773/2013)",
    [709] = "Month pass: Rehovot <> Tel-Aviv / [Egged, Superbus]",
    [711] = "Semester A pass: Rehovot <> Tel-Aviv / [Egged, Superbus] / (students only)",
    [712] = "Semester B pass: Rehovot <> Tel-Aviv / [Egged, Superbus] / (students only)",
    [713] = "Annual pass: Rehovot <> Tel-Aviv / [Egged, Superbus] / (students only)",
    [740] = "Month/Week/Day pass: Reform zone 501 + 502 - Eastern Galilee / [Egged, Nativ Express, Superbus, Golan Regional Council]",
    [741] = "Month/Week/Day pass: FULL Metropolis Haifa + Golan Heights + Circular Kineret + Upper Galilee - Ring 1, 2.1, 2.2, 3.1, 3.2, 3.3, 3.4 + zone 501, 502 / [Superbus, Golan Regional Council, Nativ Express, Egged, Israel Railways]",
    [742] = "Month/Week/Day pass: Reform zone 501 - Central and Northern Golan Heights + Upper Galilee / [Egged, Nativ Express, Superbus, Golan Regional Council]",
    [743] = "Month/Week/Day pass: Reform zone 502 - Circular Kineret + Southern Golan Heights / [Egged, Nativ Express, Superbus, Golan Regional Council]",
    [745] = "Month/Week/Day pass: Reform zone 601 + 602 - Afula region + Beit She'an region / [Superbus, Nativ Express, Egged]",
    [746] = "Month/Week/Day pass: Reform zone 602 - Beit She'an region / [Superbus, Egged]",
    [747] = "Month/Week/Day pass: Reform zone 601 - Afula region / [Superbus, Nativ Express, Egged]",
    [748] = "Month/Week/Day pass: Reform zone 702 - Hadera region / [Kavim, Afikim, Egged, Israel Railways]",
    [749] = "Month/Week/Day pass: Reform zone 701 - Harish + Wadi Ara region / [Afikim, Kavim, Metropoline, Egged]",
    [750] = "Month/Week/Day pass: Reform zone 802 - Kiryat Gat region / [Metropoline, Nativ Express, Egged, Israel Railways] / (including students)",
    [751] = "Month/Week/Day pass: Reform zone 801 - Ashkelon region / [Afikim, Metropoline, Egged, Egged Transport, Israel Railways] / (including students)",
    [752] = "Month/Week/Day pass: Reform zone 801 + 802 - Ashkelon region + Kiryat Gat region / [Afikim, Metropoline, Nativ Express, Egged Transport, Egged, Israel Railways] / (including students)",
    [753] = "Month/Week/Day pass: Dan Region - Samaria - Ring 3.4 / [Egged Transport, Afikim] / (including students)",
    [754] = "Month/Week/Day pass: Metropolis Jerusalem - Gush Shila - Ring 3.5 / [Egged Transport, Egged, Afikim]",
    [755] = "Month/Week/Day pass: Reform zone 701 - Harish <> Hadera / [Afikim, Kavim, Metropoline, Egged, Israel Railways]",
    [756] = "Day pass: Metropolis Be'er Sheva: Eilat <> Arava <> Be'er Sheva - Ring 1, 2.2, 2.3, 3.2, 3.3, zone 811/903, 901, 902 / [Dan Be'er Sheva, Egged, Metropoline]",
    [811] = "Semester pass: South / [Egged, Metrodan, Metropoline, Egged Transport] / (students only)",
    [812] = "Annual pass: South / [Egged, Metrodan, Metropoline, Egged Transport] / (students only)",
    [821] = "Amount of 2 rides - Tel-Aviv <> Be'er Sheva / [Metropoline, Egged Transport]",
    [900] = "[Free travel] Israel Railways - Free travel / [Israel Railways] / (internal)",
    [901] = "Day pass: Israel Rail + Dan Region - senior citizen / [Israel Railways, Dan, Egged, Kavim, Metropoline] / (sold by Israel Railways)",
    [902] = "Day pass: Israel Rail + Dan Region - standard / [Israel Railways, Dan, Egged, Kavim, Metropoline] / (sold by Israel Railways)",
    [903] = "Month pass: Israel Rail + Dan Region - Ring 1 - senior citizen - reform / [Israel Railways, Dan, Egged, Kavim, Metropoline] / (sold by Israel Railways)",
    [904] = "Month pass: Israel Rail + Dan Region - Extended - Ring 1, 2.1, 2.2, 2.3 - senior citizen - reform / [Israel Railways, Dan, Egged, Kavim, Metropoline] / (sold by Israel Railways)",
    [905] = "Month pass: Israel Rail + Dan Region Ring 1 - adult - reform / [Israel Railways, Dan, Egged, Kavim, Metropoline] / (sold by Israel Railways)",
    [906] = "Month pass: Israel Rail + Dan Region - Extended - Ring 1, 2.1, 2.2, 2.3 - adult - reform / [Israel Railways, Dan, Egged, Kavim, Metropoline] / (sold by Israel Railways)",
    [907] = "Month pass: Israel Rail + Dan Region - Ring 1 - senior citizen - special / [Israel Railways, Dan, Egged, Kavim, Metropoline] / (sold by Israel Railways)",
    [908] = "Month pass: Israel Rail + Dan Region - Ring 1 - senior citizen - standard / [Israel Railways, Dan, Egged, Kavim, Metropoline] / (sold by Israel Railways)",
    [909] = "Month pass: Israel Rail + Dan Region - Extended - Ring 1, 2.1, 2.2, 2.3 - senior citizen - special / [Israel Railways, Dan, Egged, Kavim, Metropoline] / (sold by Israel Railways)",
    [910] = "Month pass: Israel Rail + Dan Region - Extended - Ring 1, 2.1, 2.2, 2.3 - senior citizen - standard / [Israel Railways, Dan, Egged, Kavim, Metropoline] / (sold by Israel Railways)",
    [911] = "Month pass: Israel Rail + Dan Region - Ring 1 - adult - special / [Israel Railways, Dan, Egged, Kavim, Metropoline] / (sold by Israel Railways)",
    [912] = "Month pass: Israel Rail + Dan Region - Ring 1 - adult - standard / [Israel Railways, Dan, Egged, Kavim, Metropoline] / (sold by Israel Railways)",
    [913] = "Month pass: Israel Rail + Dan Region - Ring 1 - Ring 1, 2.1, 2.2, 2.3 - adult - special / [Israel Railways, Dan, Egged, Kavim, Metropoline] / (sold by Israel Railways)",
    [914] = "Month pass: Israel Rail + Dan Region - Extended - Ring 1, 2.1, 2.2, 2.3 - adult - standard / [Israel Railways, Dan, Egged, Kavim, Metropoline] / (sold by Israel Railways)",
    [925] = "Month pass: Israel Rail + Metropolis Haifa - senior citizen / [Israel Railways, Egged] / (sold by Israel Railways)",
    [926] = "Month pass: Israel Rail + Metropolis Haifa - adult / [Israel Railways, Egged] / (sold by Israel Railways)",
    [935] = "Month pass: Israel Rail + Shoham <> Ben-Gurion - senior citizen / [Israel Railways, Superbus] / (sold by Israel Railways)",
    [936] = "Month pass: Israel Rail + Shoham <> Ben-Gurion - adult / [Israel Railways, Superbus] / (sold by Israel Railways)",
    [940] = "Single ticket: Israel Rail + Samaria lines / [Israel Railways, Afikim] / (sold by Israel Railways)",
    [960] = "Month pass: Israel Rail + Be'er Sheva / [Israel Railways, Metrodan] / (sold by Israel Railways)",
    [962] = "Month pass: Israel Rail + Netanya / [Israel Railways, Egged Transport] / (sold by Israel Railways)",
    [964] = "Month pass: Israel Rail + Rehovot / [Israel Railways, Egged] / (sold by Israel Railways)",
    [966] = "Month pass: Israel Rail + Lod / [Israel Railways, Connex, Superbus] / (sold by Israel Railways)",
    [967] = "Month pass: Israel Rail + Ramla-Lod (extended) / [Israel Railways, Connex, Superbus] / (sold by Israel Railways)",
    [968] = "Month pass: Israel Rail + Ashkelon / [Israel Railways, Egged Transport] / (sold by Israel Railways)",
    [970] = "Month pass: Israel Rail + Kiryat Gat / [Israel Railways, Egged Transport] / (sold by Israel Railways)",
    [972] = "Month pass: Israel Rail + Hadera / [Israel Railways, Egged, Nativ Express] / (sold by Israel Railways)",
    [974] = "Month pass: Israel Rail + Beit Yehoshua/Netanya / [Israel Railways, Nativ Express] / (sold by Israel Railways)",
    [976] = "Month pass: Israel Rail + Yavne West/East / [Israel Railways, Connex] / (sold by Israel Railways)",
    [978] = "Month pass: Israel Rail + Ashdod / [Israel Railways, Egged Transport] / (sold by Israel Railways)",
    [980] = "Month pass: Israel Rail + Kiryat Motzkin / [Israel Railways, Egged] / (sold by Israel Railways)",
    [982] = "Month pass: Israel Rail + Akko / [Israel Railways, Egged] / (sold by Israel Railways)",
    [984] = "Month pass: Israel Rail + Nahariya / [Israel Railways, Nativ Express] / (sold by Israel Railways)",
    [986] = "Month pass: Israel Rail + Hadera / [Israel Railways, Nativ Express] / (sold by Israel Railways)",
    [988] = "Month pass: Israel Rail + Ceasarea/Pardes Hana / [Israel Railways, Nativ Express] / (sold by Israel Railways)",
    [990] = "Month pass: Israel Rail + Binyamina / [Israel Railways, Nativ Express] / (sold by Israel Railways)",
    [999] = "Israel Rail IDF test / [Israel Railways]",
    [1001] = "Month/Day pass: Kiryat Shmona / [Egged]",
    [1007] = "Month pass: Carmiel urban / [Egged]", --overlap 563
    [1026] = "Month pass: Pardes Hana urban / [Egged]",
    [1074] = "Month pass: Nes Tsiyona urban / [Egged]",
    [1085] = "Month/Day pass: Eilat / [Egged]"
}