.TH CARDPEEK 1

.SH NAME 
cardpeek \- A gui tool to explore the contents of ISO 7816 smart cards.

.SH SYNOPSIS 
.B cardpeek 

.SH DESCRIPTION 

Cardpeek is a tool to read the contents of ISO7816 smart cards.
It features a GTK GUI to represent card data is a tree view, and is
extendable with a scripting language (LUA).
 
The goal of this project is to allow smart card owners to be better
informed about what type of personal information is stored in these
devices.
 
This is not a real man-page, see included PDF documentation 
.B cardpeek_ref.en.pdf
available here:
 
http://cardpeek.googlecode.com/files/cardpeek_ref.en.pdf

or in your in your system 
.B doc/
directory (e.g. /usr/share/doc/cardpeek).

.SH COPYRIGHT 
cardpeek is Copyright (c) 2009-2013 L1L1@gmx.com.

cardpeek is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

cardpeek is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see http://www.gnu.org/licenses/.

.SH AUTHORS 
Alain Pannetrat <L1L1@gmx.com>

