-- 
-- This file is automatically generated by Cardpeek.
-- It holds cardpeek configuration paramters, which are stored in the
-- lua 'config' table.
-- 
-- See cardpeekrc.lua for adding your own functions and variables to
-- cardpeek.
-- 
cardpeek = {
  ['smartcard_list'] = {
    ['url'] = "http://ludovic.rousseau.free.fr/softwares/pcsc-tools/smartcard_list.txt",
    ['next_update'] = 1372374955,
    ['auto_update'] = true,
  },
}
-- end --
