-- 
-- This file is automatically generated by Cardpeek.
-- It holds cardpeek configuration parameters, which are stored in the
-- lua 'cardpeek' table.
-- 
-- See cardpeekrc.lua for adding your own functions and variables to
-- cardpeek.
-- 
cardpeek = {
  ['updates'] = {
    ['first_update'] = 1408049340,
    ['auto_update'] = true,
    ['next_update'] = 1416301647,
    ['url'] = "http://downloads.pannetrat.com/updates/cardpeek.update",
  },
}

dofile('scripts/lib/apdu.lua')
-- end --
