.TH CARDPEEK 1

.SH NAME 
cardpeek \- A gui tool to explore the contents of ISO 7816 smart cards.

.SH SYNOPSIS 
.B cardpeek 
.RB [\fIoptions\fR]

.SH DESCRIPTION 
.PP
Cardpeek is a tool to read the contents of ISO7816 smart cards.
It features a GTK+ GUI to represent card data is a tree view, and is
extendable with a scripting language (LUA).
.TP
\fB\-c\fR, \fB\-\-console\fR
Run Cardpeek in console mode, without the GTK+ GUI.
.TP
\fB\-r\fR, \fB\-\-reader\fR=\fIREADER\fR
Connect to the reader identified by READER.
.TP
\fB\-e\fR, \fB\-\-exec\fR=\fICOMMAND\fR
Execute the lua commands described in COMMAND.
.TP
\fB\-v\fR, \fB\-\-version\fR
Print version info and list of detected smart card readers.
.PP
The goal of this project is to allow smart card owners to be better
informed about what type of personal information is stored in these
devices.

.PP
This tool is capable of reading the contents of the following types of cards:
.IP \[bu]
EMV "chip and PIN" bank cards, including:
.RS
.IP \[bu]
VISA, MasterCard, CB and UK Post Office Account contact cards;
.IP \[bu]
PayWave (VISA) and PayPass (MasterCard) contactless cards;
.RE
.IP \[bu]
Electronic/Biometric passports, which have an embedded contactless chip;
.IP \[bu]
The Belgian eID card;
.IP \[bu]
Calypso transport cards including:
.RS
.IP \[bu]
Navigo transport cards used in Paris;
.IP \[bu]
MOBIB cards used in Brussels;
.IP \[bu]
RavKav cards used in Israel;
.IP \[bu]
VIVA cards used in Lisbon;
.RE
.IP \[bu]
GSM SIM cards (without USIM data used in recent cards);
.IP \[bu]
Vitale 2, the French health card.
.IP \[bu]
Moneo, the French electronic purse;
.IP \[bu]
Driver Tachograph cards;
.IP \[bu]
OpenPGP Cards (beta);
 
.PP
This is not a real man-page, for more detailed information see 
included PDF documentation 
.B cardpeek_ref.en.pdf
available online here:
 
http://cardpeek.googlecode.com/files/cardpeek_ref.en.pdf

or in your in your system 
.B doc/
directory (e.g. /usr/share/doc/cardpeek).

.SH COPYRIGHT 
Cardpeek is Copyright (c) 2009-2015 Alain Pannetrat.

Cardpeek is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

As an exemption to the GNU General Public License, compiling, 
linking, and/or using OpenSSL is allowed.

Cardpeek is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see http://www.gnu.org/licenses/.

.SH AUTHORS 
Alain Pannetrat <L1L1@gmx.com>

